//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeImageMap
    {
        public int EmployeeId { get; set; }
        public System.Guid ImageId { get; set; }
        public bool Active { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual tblImage tblImage { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
