//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LogMessage { get; set; }
    }
}
